CREATE TABLE IF NOT EXISTS person_dossiers (
    dossier_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL UNIQUE REFERENCES persons(person_id),
    sequence_no INTEGER NOT NULL,
    file_path TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'foundational_v0.1',
    evidence_policy TEXT NOT NULL,
    generated_from_migration TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_person_dossiers_sequence ON person_dossiers(sequence_no);

INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS001','P0040',1,'dossiers/foundational/01_P0040_abu-al-qasem-khan-naser-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS002','P0014',2,'dossiers/foundational/02_P0014_mahmoud-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS003','P0004',3,'dossiers/foundational/03_P0004_abdollah-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS004','P0003',4,'dossiers/foundational/04_P0003_mostafa-qoli-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS005','P0005',5,'dossiers/foundational/05_P0005_mohtaj-ali-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS006','P0006',6,'dossiers/foundational/06_P0006_mansur-ali-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS007','P0008',7,'dossiers/foundational/07_P0008_gholamhossein-khan-amiri-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS008','P0007',8,'dossiers/foundational/08_P0007_gholam-ali-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS009','P0009',9,'dossiers/foundational/09_P0009_dr-alireza-amiri-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS010','P0001',10,'dossiers/foundational/10_P0001_haji-mohammad-khan-jeyhunabadi.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS011','P0002',11,'dossiers/foundational/11_P0002_mohammad-baqer-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS012','P0011',12,'dossiers/foundational/12_P0011_mohammad-hossein-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS013','P0018',13,'dossiers/foundational/13_P0018_rustam-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS014','P0019',14,'dossiers/foundational/14_P0019_ali-khan-nosrat-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS015','P0020',15,'dossiers/foundational/15_P0020_ali-naqi-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS016','P0022',16,'dossiers/foundational/16_P0022_mohammad-hossein-khan-hosam-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS017','P0023',17,'dossiers/foundational/17_P0023_zeyn-al-abedin-khan-hosam-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS018','P0024',18,'dossiers/foundational/18_P0024_gholamreza-khan-ehtesham-al-saltaneh-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS019','P0028',19,'dossiers/foundational/19_P0028_abdollah-khan-sarem-al-saltaneh-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS020','P0031',20,'dossiers/foundational/20_P0031_amanollah-khan-baha-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS021','P0032',21,'dossiers/foundational/21_P0032_hossein-qoli-khan-zia-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS022','P0030',22,'dossiers/foundational/22_P0030_ahmad-khan-sartip-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS023','P0013',23,'dossiers/foundational/23_P0013_nabi-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS024','P0012',24,'dossiers/foundational/24_P0012_hossein-qoli-khan-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
INSERT INTO person_dossiers (dossier_id,person_id,sequence_no,file_path,status,evidence_policy,generated_from_migration,created_at,updated_at) VALUES ('DOS025','P0037',25,'dossiers/foundational/25_P0037_alireza-khan-baha-al-molk-gharagozloo.md','foundational_v0.1','Text-first: narrative text and explicit captions are primary; diagram-only relationships require textual corroboration.','0007','2026-07-11T00:00:00Z','2026-07-11T00:00:00Z') ON CONFLICT(person_id) DO UPDATE SET sequence_no=excluded.sequence_no,file_path=excluded.file_path,status=excluded.status,evidence_policy=excluded.evidence_policy,generated_from_migration=excluded.generated_from_migration,updated_at=excluded.updated_at;
