-- 0050_import_remaining_family_verified_photos_batch3.sql
-- Archive v2.9.7 — Remaining family-verified Facebook photographs + cleanup batch.
-- No genealogy changes and no new person nodes.
-- Unresolved identities are preserved as visible Gallery artifacts without forced P-ID linkage.

PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO artifacts(
    artifact_id, source_id, printed_page, artifact_type, title, caption_fa,
    description, transcription_status, confidence, file_reference, notes
) VALUES
('A0237','S0204','30-31','photograph',
 'Hassan Ali Khan Zia al-Molk Farmand',
 'HassanAli khan Ziamolk Farmand (pedar bozorg)',
 'Family-verified individual photograph identified in the supplied compilation as Hassan Ali Khan Zia al-Molk Farmand.',
 'not_applicable','confirmed','A0237.jpg',
 'VERIFIED family identification. No safe canonical P-ID established; visible globally without forced linkage.'),
('A0238','S0204','32','photograph',
 'Ahmad Khan Gharagozloo Farmand — cavalry command context',
 'Ahmad khan Gharagozloo .Farmandare savare nezam dar khorram abad.(pedar bozorg)1287-1351',
 'Family-verified photograph identified as Ahmad Khan Gharagozloo Farmand in a mounted military group at Khorramabad.',
 'not_applicable','confirmed','A0238.jpg',
 'VERIFIED family identification. No safe canonical P-ID established; visible globally without forced linkage.'),
('A0239','S0204','59-60','photograph',
 'Mohammad Baqer Khan Gharagozloo — Amir Mo''tamed / Enayat al-Saltaneh',
 'محمد باقر خان قراگزلو امیر معتمد / عنایت السلطنه',
 'Family-verified individual portrait. The identity is deliberately not conflated with P0002, the older Hajilou Mohammad Baqer Khan.',
 'not_applicable','confirmed','A0239.jpg',
 'VERIFIED family identification. Exact canonical P-ID unresolved.'),
('A0240','S0204','61','photograph',
 'Amirzadeh Khanom — daughter of Hossein Khan Hesam al-Molk I',
 'امیرزاده خانم، دختر حسین خان حسام الملک اول و همسر محمود خان پیران / عنایت الملک',
 'Family-verified pair of supplied photographs of Amirzadeh Khanom.',
 'not_applicable','confirmed','A0240.jpg',
 'VERIFIED family identification. No canonical P-ID currently assigned.'),
('A0241','S0204','63-64','photograph',
 'Zeyn al-Abedin Khan Gharagozloo — Amir Afkham',
 'زین العابدین خان قراگزلو (امیر افخم)',
 'Family-verified historical portrait of Zeyn al-Abedin Khan Amir Afkham.',
 'not_applicable','confirmed','A0241.jpg',
 'VERIFIED family identification; linked to canonical P0023.'),
('A0242','S0204','68-69','photograph',
 'Nosratollah Khan Gharagozloo — Nosrat al-Molk',
 'نصرت الله خان قراگزلو - نصرت الملک',
 'Family-verified individual portrait of Nosratollah Khan Nosrat al-Molk, identified as a Hamadan representative in the first Constituent Assembly.',
 'not_applicable','confirmed','A0242.jpg',
 'VERIFIED family identification. Exact canonical P-ID unresolved.'),
('A0243','S0204','70-71','photograph',
 'Zeyn al-Abedin Khan Gharagozloo — Amir Afkham, second portrait',
 'زین العابدین خان قراگزلو (امیر افخم)',
 'Second family-verified historical image of Zeyn al-Abedin Khan Amir Afkham.',
 'not_applicable','confirmed','A0243.jpg',
 'VERIFIED family identification; linked to canonical P0023.'),
('A0244','S0204','72-73','photograph',
 'Family group of Amir Afkham',
 'خانواده امیر افخم؛ غلامعلی خان حسام الملک سوم و غلامرضا خان احتشام الدوله در میان افراد شناسایی شده',
 'Family-verified multi-person family photograph. The supplied caption identifies Etrat al-Saltaneh, Gholam Ali Khan Hesam al-Molk III, Vali-Zadeh Khanom, and Gholamreza Khan Ehtesham al-Dowleh.',
 'not_applicable','confirmed','A0244.jpg',
 'VERIFIED family group. Canonical links added only for P0170 and P0024; unresolved relatives remain in caption.'),
('A0245','S0204','75-76','photograph',
 'Gholamhossein Khan Amiri Gharagozloo',
 'غلامحسین خان امیری قراگزلو، فرزند محتاجعلی خان امیر ارفع',
 'Family-verified clear individual portrait of Gholamhossein Khan Amiri Gharagozloo.',
 'not_applicable','confirmed','A0245.jpg',
 'VERIFIED family identification; linked to P0008. Selected as primary portrait under the agreed portrait policy because it is a verified individual portrait.'),
('A0246','S0204','84-85','photograph',
 'Nosratollah Khan Gharagozloo — Nosrat al-Molk, second portrait',
 'نصرت الله خان قراگزلو - نصرت الملک',
 'Second family-verified portrait of Nosratollah Khan Nosrat al-Molk.',
 'not_applicable','confirmed','A0246.jpg',
 'VERIFIED family identification. Exact canonical P-ID unresolved.'),
('A0247','S0204','88-89','photograph',
 'Mohsen Gharagozloo with Queen Soraya — source caption',
 'محسن قراگزلو و ملکه ثریا',
 'Family-verified contextual photograph. The supplied caption names Mohsen Gharagozloo and Queen Soraya.',
 'not_applicable','confirmed','A0247.jpg',
 'VERIFIED family identification for the supplied caption; P0042 linked for Mohsen. The other person is preserved only as captioned context.'),
('A0248','S0204','90-91','photograph',
 'Unresolved family-verified historical portrait',
 NULL,
 'Historical portrait marked VERIFIED in the family compilation. The person name is not legible enough in the supplied carrier to assign a canonical identity safely.',
 'not_applicable','confirmed','A0248.jpg',
 'Keep visible in global Gallery as family-verified artifact; do not force person linkage.'),
('A0249','S0204','92-93','photograph',
 'Fazlollah Khan Gharagozloo — Entesar al-Molk',
 'فضل الله خان قراگزلو انتصار الملک',
 'Family-verified historical portrait captioned as Fazlollah Khan Gharagozloo, Entesar al-Molk.',
 'not_applicable','confirmed','A0249.jpg',
 'VERIFIED family identification. Exact canonical P-ID remains unresolved, so no forced link is created.'),
('A0250','S0204','100-101','photograph',
 'Unresolved three-person Gharagozloo family photograph',
 NULL,
 'Family-verified historical group photograph of three people. The clipped caption in the supplied carrier is insufficient for safe canonical identity binding.',
 'not_applicable','confirmed','A0250.jpg',
 'Visible globally as VERIFIED family archive material; no forced links.'),
('A0251','S0204','102-103','photograph',
 'Unresolved family-verified elder portrait',
 NULL,
 'Family-verified historical individual portrait. The supplied caption is clipped and cannot be read confidently enough for canonical linkage.',
 'not_applicable','confirmed','A0251.jpg',
 'Visible globally as VERIFIED family archive material; no forced link.'),
('A0252','S0204','104','photograph',
 'Public event including Mohsen Gharagozloo',
 'از راست به چپ: دکتر جهانشاه صالح، سپهبد غلامحسین افخمی، دکتر اقبال، دکتر علی اکبر سیاسی، ملکه ثریا، حسین علاء، محسن قراگزلو',
 'Family-verified public-event photograph with multiple captioned figures; Mohsen Gharagozloo is the archive-linked family subject.',
 'not_applicable','confirmed','A0252.jpg',
 'VERIFIED supplied caption. Only canonical Gharagozloo P0042 is linked; other public figures remain contextual names.');

INSERT OR IGNORE INTO artifact_persons(artifact_id, person_id, role, notes) VALUES
('A0241','P0023','subject','Captioned and family-verified identity.'),
('A0243','P0023','subject','Captioned and family-verified identity.'),
('A0244','P0170','subject','Caption identifies Gholam Ali Khan Hesam al-Molk III.'),
('A0244','P0024','subject','Caption identifies Gholamreza Khan Ehtesham al-Dowleh.'),
('A0245','P0008','subject','Captioned and family-verified identity.'),
('A0247','P0042','subject','Caption identifies Mohsen Gharagozloo.'),
('A0252','P0042','attendee','Caption identifies Mohsen Gharagozloo among attendees.');

INSERT OR IGNORE INTO artifact_gallery_metadata(
    artifact_id, verification_class, display_status, selection_notes
) VALUES
('A0237','family_verified','visible','Verified family identity; unresolved canonical node, global Gallery only.'),
('A0238','family_verified','visible','Verified family identity; unresolved canonical node, global Gallery only.'),
('A0239','family_verified','visible','Verified family identity; do not conflate with P0002.'),
('A0240','family_verified','visible','Verified family identity; unresolved canonical node, global Gallery only.'),
('A0241','family_verified','visible','Verified individual portrait linked to P0023; selected as P0023 primary portrait.'),
('A0242','family_verified','visible','Verified family identity; unresolved canonical node, global Gallery only.'),
('A0243','family_verified','visible','Second verified image linked to P0023.'),
('A0244','family_verified','visible','Verified family group linked to canonical identified members only.'),
('A0245','family_verified','visible','Verified individual portrait linked to P0008; selected as primary portrait under agreed policy.'),
('A0246','family_verified','visible','Second verified Nosratollah portrait; unresolved canonical node.'),
('A0247','family_verified','visible','Verified contextual photograph linked to P0042.'),
('A0248','family_verified','visible','Verified artifact; identity unresolved from clipped caption.'),
('A0249','family_verified','visible','Verified identity caption; canonical P-ID unresolved.'),
('A0250','family_verified','visible','Verified family photograph; identities unresolved from clipped caption.'),
('A0251','family_verified','visible','Verified individual photograph; identity unresolved from clipped caption.'),
('A0252','family_verified','visible','Verified event photograph; linked to P0042 only.');

-- Primary portrait selections under the archive policy:
-- verified clear individual portrait > weaker or unverified alternatives.
INSERT OR REPLACE INTO person_primary_portraits(
    person_id, artifact_id, selection_basis, selected_by, notes
) VALUES
('P0023','A0241','Family-verified clear individual portrait','archive migration 0050',
 'Selected from the verified family collection; A0243 remains a second Gallery image.'),
('P0008','A0245','Family-verified clear individual portrait','archive migration 0050',
 'Replaces the prior legacy portrait as the database-selected primary. Earlier portraits and A0219 remain preserved in the Gallery.');
